create table portfolios (id int8 generated by default as identity, name varchar(255) not null, primary key (id));
create table shares (id int8 generated by default as identity, quantity_year numeric(19, 2) not null, year varchar(255) not null, portfolio_id int8 not null, stock_id int8 not null, primary key (id));
create table stocks (id int8 generated by default as identity, isin varchar(255) not null, price_year numeric(19, 2) not null, year varchar(255) not null, primary key (id));
create table total_values (id int8 generated by default as identity, value numeric(19, 2) not null, year varchar(255) not null, portfolio_id int8 not null, primary key (id));
alter table if exists shares add constraint sharestoportfolios foreign key (portfolio_id) references portfolios;
alter table if exists shares add constraint sharestostocks foreign key (stock_id) references stocks;
alter table if exists total_values add constraint totaltoportfolios foreign key (portfolio_id) references portfolios;
